version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: db_agroconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "8080:80"
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: db_agroconnect
      DB_USER: postgres
      DB_PASSWORD: admin123
      STUDENT_NAME: "Sebastian Vargas"

volumes:
  postgres_data:
